---
author: anarcho-cyberpunk
comments:
- author: DELETED
  author_flair: null
  body: 'I was just thinking of Prometheus. Anyway, here''s something -


    http://www.paulkiritsis.net/_blog/Down_The_Rabbit_Hole/post/The_Promethean_Myth_in_Light_of_Jungian_Psychology/'
  created_utc: 1447351336.0
  distinguished: null
  id: cwxwrhk
  is_submitter: false
  parent_id: t3_3sjynl
  replies: []
  score: 2
  stickied: false
  submission: 3sjynl
  subreddit: sorceryofthespectacle
- author: DELETED
  author_flair: null
  body: "Prometheus is lucifer/demiurge/Adam Kadmon/pantheism/Eleatic Monism. \n\n\
    in other words, in some philosophical (not just gnostic, Boazy) schools, *we*\
    \ are Prometheus. We steal the fire from the gods. The soul, the spark, the light.\
    \ Traditionally, the soul is that which mediates between man and the divine.\n\
    \nEric Havelock did a translation of Prometheus as well as introductory essay\
    \ and commentary. You got some very interesting books, the most important or most\
    \ interesting to me anyways is his \"preface to Plato\". Havelock picked up on\
    \ a comment by a guy named Mims I believe, and formulated the \"literacy\" paradigm\
    \ which Marshall McLuhan picked up and ran in for a touchdown. Eric Havelock and\
    \ Walter J. Ong and a couple other people from Canada however, are the ones who\
    \ developed the \"Gutenberg galaxy\" or \"typographic mindset\". The basic premise\
    \ is that the idea of literacy reading from left to right sequentially etc. leads\
    \ to all types of profound physiological and printing on the human brain and psyche.\
    \ The topographic mindset also trans towards eschatology and then your time, thus\
    \ apocalypse. Terence McKenna it was intern profoundly influenced by this whole\
    \ trajectory of thought. All that to say that have locks translation of Prometheus\
    \ is probably worth reading. I have it somewhere and give it a go a few years\
    \ ago after I read preface to Plato but found it really dry and couldn't get the\
    \ text started. there is also a book about Prometheus and a translation by Karl\
    \ Kerlyni? Carl Jungs good friend and sometimes co-author.\n\nA couple years ago\
    \ I also tried to run down the Prometheus mythos but never could get very far\
    \ with it. I think the idea of Prometheus is a fairly late Greek invention and\
    \ it didn't ever receive that do attention that it deserves to perhaps but it's\
    \ probably a post Homeric tangent. "
  created_utc: 1447352883.0
  distinguished: null
  id: cwxxt9y
  is_submitter: false
  parent_id: t3_3sjynl
  replies: []
  score: 2
  stickied: false
  submission: 3sjynl
  subreddit: sorceryofthespectacle
- author: memearchivingbot
  author_flair: Critical Occultist
  body: Have you read Prometheus Bound?
  created_utc: 1447357954.0
  distinguished: null
  id: cwy1apz
  is_submitter: false
  parent_id: t3_3sjynl
  replies:
  - author: anarcho-cyberpunk
    author_flair: Anarcho-Post-Antineoist
    body: I haven't. Should I?
    created_utc: 1447358377.0
    distinguished: null
    id: cwy1l94
    is_submitter: true
    parent_id: t1_cwy1apz
    replies:
    - author: memearchivingbot
      author_flair: Critical Occultist
      body: Yeah. If you're looking for classical works on Prometheus that's pretty
        much the start.  It's one of my favorites and I find it relevant for the sub
        as well.  There are parallels between the fire of the gods and the system
        of alienation and abstraction of the spectacle.
      created_utc: 1447358679.0
      distinguished: null
      id: cwy1ss2
      is_submitter: false
      parent_id: t1_cwy1l94
      replies:
      - author: anarcho-cyberpunk
        author_flair: Anarcho-Post-Antineoist
        body: Interesting. I always got the impression that the fire was the opposite
          of the spectacle. Something that those in charge don't want us to have but
          we do, that helps us see reality.
        created_utc: 1447359470.0
        distinguished: null
        id: cwy2ck0
        is_submitter: true
        parent_id: t1_cwy1ss2
        replies: []
        score: 1
        stickied: false
        submission: 3sjynl
        subreddit: sorceryofthespectacle
      score: 2
      stickied: false
      submission: 3sjynl
      subreddit: sorceryofthespectacle
    score: 1
    stickied: false
    submission: 3sjynl
    subreddit: sorceryofthespectacle
  score: 2
  stickied: false
  submission: 3sjynl
  subreddit: sorceryofthespectacle
- author: oraxular
  author_flair: Occultist
  body: It's been mentioned here before but I have to recommend Alan Moore's *Promethea*,
    especially because I happen to be rereading the series right now. It deals with
    a feminized version of Prometheus as the Light Bringer and lays down a really
    great understanding of magic as well
  created_utc: 1447398433.0
  distinguished: null
  id: cwyoegk
  is_submitter: false
  parent_id: t3_3sjynl
  replies:
  - author: anarcho-cyberpunk
    author_flair: Anarcho-Post-Antineoist
    body: I think a female Prometheus makes as much sense as a male one. Prometheus
      seems to occupy that same combination trickster/Creator role as someone like
      Hermes Trismegistus. Creators tend to be too infinitely complex to be defined
      as male or female and tricksters tend to blur the line in an intentional way.
    created_utc: 1447429383.0
    distinguished: null
    id: cwyyfj2
    is_submitter: true
    parent_id: t1_cwyoegk
    replies: []
    score: 1
    stickied: false
    submission: 3sjynl
    subreddit: sorceryofthespectacle
  score: 2
  stickied: false
  submission: 3sjynl
  subreddit: sorceryofthespectacle
- author: lawoffour
  author_flair: null
  body: 'https://www.youtube.com/watch?v=x7cwWoK0gz4


    "900000 years ago an alien videotaped his attempts to educate a caveman."'
  created_utc: 1447433746.0
  distinguished: null
  id: cwz1792
  is_submitter: false
  parent_id: t3_3sjynl
  replies: []
  score: 2
  stickied: false
  submission: 3sjynl
  subreddit: sorceryofthespectacle
created_utc: 1447348603.0
distinguished: null
id: 3sjynl
link_flair_text: null
locked: false
name: t3_3sjynl
num_comments: 9
over_18: true
permalink: /r/sorceryofthespectacle/comments/3sjynl/prometheus/
pinned: false
score: 3
selftext: I've become fascinated with the figure of Prometheus since reading Frankenstein.
  Can anyone recommend some reading on the subject, both the classic works and postmodern
  interpretations, religions that have venerated Prometheus (if any) and so on?
spoiler: false
title: Prometheus
upvote_ratio: 1.0
url: https://www.reddit.com/r/sorceryofthespectacle/comments/3sjynl/prometheus/
---
## [t3_3sjynl](https://www.reddit.com/r/sorceryofthespectacle/comments/3sjynl/prometheus/)
I've become fascinated with the figure of Prometheus since reading Frankenstein. Can anyone recommend some reading on the subject, both the classic works and postmodern interpretations, religions that have venerated Prometheus (if any) and so on?

---

submitted to [r/Conjuring the Apocalypse ](https://www.reddit.com/r/Conjuring the Apocalypse ) by [u/anarcho-cyberpunk](https://www.reddit.com/user/anarcho-cyberpunk)